INSERT INTO product
    (prod_name, prod_desc, stock_amount, unit_price, photo)
VALUES
    ('Durian', 'Popular in Southeast Asia, the durian is named after its spiky exterior. The husk, distinct smell, and size of the durian make the fruit distinctive.', '20', '45.00','view/images/durian.jpg'),
    ('Rambutan', 'The rambutan is named after the hair skin covering it. The fruit inside is sweet, and contains a seed inside.', '30', '5.00','view/images/Rambutan.jpg'),
    ('Mangosteen', 'The mangosteens fruity interior is tangy and sweet, while the hard purple rind is not edible.', '22', '2.50','view/images/PurpleMangosteen.jpg'),
    ('Salak', 'Snake fruit can be compared to pineapple in taste, with a tangy and sweet flavour. The name is from the scaly skin covering the fruit.', '34', '8.50','view/images/SnakeFruit.jpg'),
    ('Carambola', ' The star fruit is named for it is star-like appearance when cut in cross-section. The entire fruit can be eaten, providing juicy flavour with a crunch.', '11', '8.00','view/images/StarFruit.jpg'),
    ('Dragonfruit', 'The dragonfruits name comes from the appearance of dragon flames or scales on its exterior. The flavour is mild and bland, with the fun coming from distinctive exterior.', '5', '35.50','view/images/Dragonfruit.jpg'),
    ('Longan', ' The longans name comes from how the shelled fruit looks like an eyeball (due to a single black seed inside). The taste is sweet and comparable to that of a lychee.', '50', '1.00','view/images/Longan.jpg'),
    ('Lychee', 'Lychee fruits are small and very sweet. The reddish outside is not edible, but the interior is typically eaten when fresh.', '49', '1.20','view/images/Lychee.jpg'),
    ('Breadfruit', 'Popular in Southeast Asia, the durian is named after its spiky exterior. The husk, distinct smell, and size of the durian make the fruit distinctive.', '15', '20.00','view/images/Breadfruit.jpg'),
    ('Indian Mulberry', ' The fruit has a bitter flavour and a strong smell (hence the name), but the seeds are can be roasted and eaten.', '9', '12.00','view/images/CheeseFruit.jpg'),
    ('Pomelo', 'The pomelo is a large citruis fruit contained in a thick rind. The flavour is sweet, and both the interior and the rind are edible.', '4', '40.50','view/images/Pomelo.jpg'),
    ('Sapodilla ', 'Popular in Southeast Asia, the durian is named after its spiky exterior. The husk, distinct smell, and size of the durian make the fruit distinctive.', '32', '1.00','view/images/Sapodilla.jpg'),
    ('Water Apple', 'The water apple is actually a berry. It is a juicy and crunchy fruit.', '15', '12.00','view/images/WaterApple.jpg'),
    ('Guava', 'Guavas commonly have green exteriors and pink interiors when ripe. It can be served raw as is, with some spices, or with sugar.', '18', '15.00','view/images/Guava.jpg'),
    ('Kumquat', 'Kumquats are similar in size to large olives, but they look like oranges. The fruit is often turned into jelly or marmalade, but can also be eaten cooked.', '14', '1.00','view/images/Kumquat.jpg'),
    ('Waxberry', 'This fruit provides a sweet, but tart flavour with one seed inside. The fruit can be eaten dried or fresh, or even fermented into liquor.', '29', '1.00','view/images/Yangmei.jpg'),
    ('Soursop', ' This fruits flavour can be compared to combining a pineapple and a strawberry. The texture is creamy like a banana or coconut.', '41', '5.50','view/images/Soursop.jpg'),
    ('Pulasan', 'This fruit is sweet and typically eaten fresh. The seed inside can also be eaten raw.', '37', '2.00','view/images/Pulasan.jpg'),
    ('Kaffir Lime', 'The green skin of this fruit is bumpy and rough. The exterior, zest, and the leaves are all edible.', '42', '2.50','view/images/KaffirLime.jpg'),
    ('Sugar Apple', 'The flesh of the fruit is sweet, and could be compared to custard in taste. There may be multiple seeds inside that are not edible.', '29', '20.00','view/images/SugarApple.jpg');

INSERT INTO country
    (country_id, country_name)
VALUES
('AF','Afghanistan'),
('AX','Aland Islands'),
('AL','Albania'),
('DZ','Algeria'),
('AS','American Samoa'),
('AD','Andorra'),
('AO','Angola'),
('AI','Anguilla'),
('AQ','Antarctica'),
('AG','Antigua and Barbuda'),
('AR','Argentina'),
('AM','Armenia'),
('AW','Aruba'),
('AU','Australia'),
('AT','Austria'),
('AZ','Azerbaijan'),
('BS','Bahamas'),
('BH','Bahrain'),
('BD','Bangladesh'),
('BB','Barbados'),
('BY','Belarus'),
('BE','Belgium'),
('BZ','Belize'),
('BJ','Benin'),
('BM','Bermuda'),
('BT','Bhutan'),
('BO','Bolivia, Plurinational State of'),
('BQ','Bonaire, Sint Eustatius and Saba'),
('BA','Bosnia and Herzegovina'),
('BW','Botswana'),
('BV','Bouvet Island'),
('BR','Brazil'),
('IO','British Indian Ocean Territory'),
('BN','Brunei Darussalam'),
('BG','Bulgaria'),
('BF','Burkina Faso'),
('BI','Burundi'),
('KH','Cambodia'),
('CM','Cameroon'),
('CA','Canada'),
('CV','Cape Verde'),
('KY','Cayman Islands'),
('CF','Central African Republic'),
('TD','Chad'),
('CL','Chile'),
('CN','China'),
('CX','Christmas Island'),
('CC','Cocos (Keeling) Islands'),
('CO','Colombia'),
('KM','Comoros'),
('CG','Congo'),
('CD','Congo, the Democratic Republic of the'),
('CK','Cook Islands'),
('CR','Costa Rica'),
('HR','Croatia'),
('CU','Cuba'),
('CW','Curaçao'),
('CY','Cyprus'),
('CZ','Czech Republic'),
('DK','Denmark'),
('DJ','Djibouti'),
('DM','Dominica'),
('DO','Dominican Republic'),
('EC','Ecuador'),
('EG','Egypt'),
('SV','El Salvador'),
('GQ','Equatorial Guinea'),
('ER','Eritrea'),
('EE','Estonia'),
('ET','Ethiopia'),
('FK','Falkland Islands (Malvinas)'),
('FO','Faroe Islands'),
('FJ','Fiji'),
('FI','Finland'),
('FR','France'),
('GF','French Guiana'),
('PF','French Polynesia'),
('TF','French Southern Territories'),
('GA','Gabon'),
('GM','Gambia'),
('GE','Georgia'),
('DE','Germany'),
('GH','Ghana'),
('GI','Gibraltar'),
('GR','Greece'),
('GL','Greenland'),
('GD','Grenada'),
('GP','Guadeloupe'),
('GU','Guam'),
('GT','Guatemala'),
('GG','Guernsey'),
('GN','Guinea'),
('GW','Guinea-Bissau'),
('GY','Guyana'),
('HT','Haiti'),
('HM','Heard Island and McDonald Islands'),
('VA','Holy See (Vatican City State)'),
('HN','Honduras'),
('HK','Hong Kong'),
('HU','Hungary'),
('IS','Iceland'),
('IN','India'),
('ID','Indonesia'),
('IR','Iran, Islamic Republic of'),
('IQ','Iraq'),
('IE','Ireland'),
('IM','Isle of Man'),
('IL','Israel'),
('IT','Italy'),
('JM','Jamaica'),
('JP','Japan'),
('JE','Jersey'),
('JO','Jordan'),
('KZ','Kazakhstan'),
('KE','Kenya'),
('KI','Kiribati'),
('KR','Korea, Republic of'),
('KW','Kuwait'),
('KG','Kyrgyzstan'),
('LV','Latvia'),
('LB','Lebanon'),
('LS','Lesotho'),
('LR','Liberia'),
('LY','Libya'),
('LI','Liechtenstein'),
('LT','Lithuania'),
('LU','Luxembourg'),
('MO','Macao'),
('MK','Macedonia, the former Yugoslav Republic of'),
('MG','Madagascar'),
('MW','Malawi'),
('MY','Malaysia'),
('MV','Maldives'),
('ML','Mali'),
('MT','Malta'),
('MH','Marshall Islands'),
('MQ','Martinique'),
('MR','Mauritania'),
('MU','Mauritius'),
('YT','Mayotte'),
('MX','Mexico'),
('FM','Micronesia, Federated States of'),
('MD','Moldova, Republic of'),
('MC','Monaco'),
('MN','Mongolia'),
('ME','Montenegro'),
('MS','Montserrat'),
('MA','Morocco'),
('MZ','Mozambique'),
('MM','Myanmar'),
('NA','Namibia'),
('NR','Nauru'),
('NP','Nepal'),
('NL','Netherlands'),
('NC','New Caledonia'),
('NZ','New Zealand'),
('NI','Nicaragua'),
('NE','Niger'),
('NG','Nigeria'),
('NU','Niue'),
('NF','Norfolk Island'),
('MP','Northern Mariana Islands'),
('NO','Norway'),
('OM','Oman'),
('PK','Pakistan'),
('PW','Palau'),
('PS','Palestinian Territory, Occupied'),
('PA','Panama'),
('PG','Papua New Guinea'),
('PY','Paraguay'),
('PE','Peru'),
('PH','Philippines'),
('PN','Pitcairn'),
('PL','Poland'),
('PT','Portugal'),
('PR','Puerto Rico'),
('QA','Qatar'),
('RE','Réunion'),
('RO','Romania'),
('RU','Russian Federation'),
('RW','Rwanda'),
('BL','Saint Barthélemy'),
('SH','Saint Helena, Ascension and Tristan da Cunha'),
('KN','Saint Kitts and Nevis'),
('LC','Saint Lucia'),
('MF','Saint Martin (French part)'),
('PM','Saint Pierre and Miquelon'),
('VC','Saint Vincent and the Grenadines'),
('WS','Samoa'),
('SM','San Marino'),
('ST','Sao Tome and Principe'),
('SA','Saudi Arabia'),
('SN','Senegal'),
('RS','Serbia'),
('SC','Seychelles'),
('SL','Sierra Leone'),
('SG','Singapore'),
('SX','Sint Maarten (Dutch part)'),
('SK','Slovakia'),
('SI','Slovenia'),
('SB','Solomon Islands'),
('SO','Somalia'),
('ZA','South Africa'),
('GS','South Georgia and the South Sandwich Islands'),
('SS','South Sudan'),
('ES','Spain'),
('LK','Sri Lanka'),
('SD','Sudan'),
('SR','Suriname'),
('SJ','Svalbard and Jan Mayen'),
('SZ','Swaziland'),
('SE','Sweden'),
('CH','Switzerland'),
('SY','Syrian Arab Republic'),
('TW','Taiwan, Province of China'),
('TJ','Tajikistan'),
('TZ','Tanzania, United Republic of'),
('TH','Thailand'),
('TL','Timor-Leste'),
('TG','Togo'),
('TK','Tokelau'),
('TO','Tonga'),
('TT','Trinidad and Tobago'),
('TN','Tunisia'),
('TR','Turkey'),
('TM','Turkmenistan'),
('TC','Turks and Caicos Islands'),
('TV','Tuvalu'),
('UG','Uganda'),
('UA','Ukraine'),
('AE','United Arab Emirates'),
('GB','United Kingdom'),
('US','United States'),
('UM','United States Minor Outlying Islands'),
('UY','Uruguay'),
('UZ','Uzbekistan'),
('VU','Vanuatu'),
('VE','Venezuela, Bolivarian Republic of'),
('VN','Viet Nam'),
('VG','Virgin Islands, British'),
('VI','Virgin Islands, U.S.'),
('WF','Wallis and Futuna'),
('EH','Western Sahara'),
('YE','Yemen'),
('ZM','Zambia'),
('ZW','Zimbabwe');

INSERT INTO province
    (prov_id, prov_name, country_id)
VALUES
('AB','Alberta','CA'),
('BC','British Columbia','CA'),
('MB','Manitoba','CA'),
('NB','New Brunswick','CA'),
('NL','Newfoundland and Labrador','CA'),
('NS','Nova Scotia','CA'),
('ON','Ontario','CA'),
('PE','Prince Edward Island','CA'),
('QC','Quebec','CA'),
('SK','Saskatchewan','CA'),
('NT','Northwest Territories','CA'),
('NU','Nunavut','CA'),
('YT','Yukon','CA');
